### ISSUE TITLE
Improvements for "build from source" section

### ISSUE THREAD

**Issue by Yaraslaut** [ttddee/CascadeDocs#1]
Have you considered possibility of adding a script in the repository to download and install all dependencies?

In the code for building dependencies there is following code:
`cmake -DCMAKE_INSTALL_PREFIX=~/Cascade/external/OpenColorIO/install ~/Cascade/external/OpenColorIO -DOCIO_BUILD_PYTHON=OFF -DOCIO_BUILD_APPS=OFF -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_GPU_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=/usr/bin/gcc
`

install prefix and source files path defined strictly, but from the folder tree we know the relative path:
`-DCMAKE_INSTALL_PREFIX=~/Cascade/external/OpenColorIO/install ~/Cascade/external/OpenColorIO` -> `-DCMAKE_INSTALL_PREFIX= ../install  ..`

Also, I think that path to the compiler can be removed.

And, at the stage when we want to download  glslang binaries, command 
`cd ../..` 
assuming that we were following all the steps above.

Last thing, I am not sure if new lines between script code helps to read it or vice versa.

**Comment by ttddee** [comment]
Hi!

Thanks for the feedback and yes those are good suggestions. I'll revise the instructions.

**Comment by ttddee** [comment]
I have pushed a new version. Not sure about the readability without the empty lines between commands. What do you think?

Would you be willing to put a script together that automates all the steps?

**Comment by Yaraslaut** [comment]
Hi, 
I've created a pull request in main repository [here]( https://github.com/ttddee/Cascade/pull/62 ) with the script

**Comment by ttddee** [comment]
That is amazing thank you! I will look through it tomorrow.

**Comment by Yaraslaut** [comment]
I've updated documentation to guide people to use script to install dependencies #2

**Comment by ttddee** [comment]
Closing this since it's done. Great work thanks!
